image: python:3.12

variables:
    DJANGO_SETTINGS_MODULE: "core.settings.testing"
    PYTHONUNBUFFERED: "1"

cache:
    paths:
        - .pip-cache/

before_script:
    - poetry shell python3.12
    - poetry install

stages:
    - test_stage

test:
    stage: test_stage
    image: python:3.12
    tags: [test]
    script:
        - cd application
        - python3.12 manage.py makemigrations
        - poetry3.12 run pytest --disable-warnings
    artifacts:
        when: always
