image: python:3.12

variables:
    DJANGO_SETTINGS_MODULE: "core.settings.testing"
    PYTHONUNBUFFERED: "1"
    POETRY_VERSION: 1.6.1

cache:
    paths:
        - .pip-cache/

before_script:
    - apt-get update
    - apt-get install pip
    - pip install --no-cache-dir "poetry==$POETRY_VERSION"
    - poetry config virtualenvs.create false
    - poetry install

stages:
    - test_stage

test:
    stage: test_stage
    tags: [test]
    script:
        - cd application
        - python manage.py makemigrations
        - poetry run pytest --disable-warnings
    artifacts:
        when: always
