variables:
    DJANGO_SETTINGS_MODULE: "core.settings.testing"
    PYTHONUNBUFFERED: "1"

cache:
    paths:
        - .pip-cache/

stages:
    - test_stage

test:
    stage: test_stage
    image: python:3.12
    tags: [test]
    before_script:
        - pip install -r requirements.txt
    script:
        - cd application
        - python3.12 manage.py makemigrations
        - python3.12 -m pytest --disable-warnings
    artifacts:
        when: always
