image: python:3.12

services:
    - postgres:latest

variables:
    DJANGO_SETTINGS_MODULE: "core.settings.testing"
    PYTHONUNBUFFERED: "1"

cache:
    paths:
        - .pip-cache/

before_script:
    - pip install --no-cache-dir "poetry==$POETRY_VERSION"
    - poetry config virtualenvs.create false
    - poetry install

stages:
    - test

test:
    stage: test
    script:
        - poetry run pytest --disable-warnings
    artifacts:
        when: always
