variables:
    HOME: /home/gitlab-runner
    BUILD_NAME: backend

stages:
    - print
    - build
    - run_tests
    - cleanup

print_message:
    stage: print
    script:
        - echo "Hello, World!"

build:dev:
    stage: build
    script:
        - docker compose up --build

run_tests:
    stage: run_tests
    script:
        - docker exec -i bicycles-web-1 pytest

cleanup:
    stage: cleanup
    when: always
    script:
        - docker system prune --force
