image: python:3.12

services:
    - postgres:latest

variables:
    DJANGO_SETTINGS_MODULE: "core.settings.testing"
    PYTHONUNBUFFERED: "1"

cache:
    paths:
        - .pip-cache/

before_script:
    - pip install -r requirements.txt

stages:
    - test

test:
    stage: test
    script:
        - pytest
    artifacts:
        when: always
