stages:
    - print
    - build
    - run_tests

print_message:
    stage: print
    script:
        - echo "Hello, World!"

build:dev:
    stage: build
    script:
        - cp docker-compose.yaml Dockerfile .
        - docker-compose up --build

run_tests:
    stage: run_tests
    script:
        - docker exec -i bicycles-web-1 pytest
