services:
    db:
        image: postgres
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - "5432:5432"

    redis:
        image: redis

    web:
        build:
            context: .
            dockerfile: ./Dockerfile
        entrypoint: ./entrypoint.sh python manage.py runserver 0.0.0.0:8000
        # entrypoint: ./entrypoint.sh uwsgi --ini uwsgi.ini
        environment:
            - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
        ports:
            - "8000:8000"
        depends_on:
            - db

    celery_worker:
        build:
            context: .
            dockerfile: ./Dockerfile
        entrypoint: celery -A core worker --loglevel=info
        environment:
            - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
        depends_on:
            - redis
            - web

    flower:
        image: mher/flower
        ports:
            - "5555:5555"
        environment:
            CELERY_BROKER_URL: ${CELERY_BROKER_URL}
            FLOWER_PORT: 5555
        depends_on:
            - celery_worker
